version: 2.1

orbs: 
  node: circleci/node@5.0.3

jobs:
  test:
    docker:
      - image: cimg/node:18.11
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Execute Unit Tests"
          command: "npm test"
      - run:
          name: "Lint Check"
          command: "npm run lint"

workflows:
  pr:
    jobs:
      - test
