version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: "npm ci"
      - run:
          name: "Execute Unit Tests"
          command: "npm test"

workflows:
  pr:
    jobs:
      - test
